version: '3.7'

services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment: 
            - SECRET_KEY=axhg1hucf=uo1xnu8dz052bshal#4m!u(#@a-a2wnvhj_eww!-
            - DEBUG=1
        volumes: 
            - .:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db

    db:
        image: postgres:12
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
    
volumes:
    postgres_data:
